import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, FileText, LogOut, Megaphone, Palette, RefreshCw, Settings, ShieldCheck, Trash2, Pencil, Plus } from "lucide-react";
import { supabase, defaultTheme, type Settings as AppSettings, type ThemeConfig, type Ad, type SeoPage } from "./lib/supabase";
import type { Session } from "@supabase/supabase-js";
import { Button, Card, Field, Input, Select, Textarea } from "./components/ui";

type Role="admin"|"editor";

const emptyAd:Omit<Ad,"id">={placement:"header",ad_code:"",is_active:true,target_platform:"both"};
const emptySeo:Omit<SeoPage,"id">={slug:"",title:"",content:"",meta_title:"",meta_description:"",meta_keywords:"",is_published:false};

function App(){
 const qc=useQueryClient();
 const [session,setSession]=useState<Awaited<ReturnType<NonNullable<typeof supabase>["auth"]["getSession"]>>["data"]["session"]|null>(null);
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [tab,setTab]=useState("overview");
 const [toast,setToast]=useState(""); const [analytics,setAnalytics]=useState(""); const [theme,setTheme]=useState<ThemeConfig>(defaultTheme);
 const [ad,setAd]=useState(emptyAd); const [editingAd,setEditingAd]=useState<string|null>(null);
 const [seo,setSeo]=useState(emptySeo); const [editingSeo,setEditingSeo]=useState<string|null>(null);

 useEffect(()=>{ if(!supabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe(); },[]);
 useEffect(()=>{ if(toast){const t=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(t)}},[toast]);

 const profile=useQuery({queryKey:["profile",session?.user.id],enabled:!!supabase&&!!session,queryFn:async()=>{const {data,error}=await supabase!.from("profiles").select("role,display_name").eq("id",session!.user.id).single();if(error)throw error;return data as {role:Role;display_name:string|null}}});
 const role=profile.data?.role;
 const settings=useQuery({queryKey:["settings"],enabled:!!supabase&&role==="admin",queryFn:async()=>{const {data,error}=await supabase!.from("app_settings").select("id,google_analytics_id,theme_config").eq("id",true).single();if(error)throw error;return data as AppSettings}});
 const ads=useQuery({queryKey:["ads"],enabled:!!supabase&&role==="admin",queryFn:async()=>{const {data,error}=await supabase!.from("ads_management").select("*").order("placement");if(error)throw error;return data as Ad[]}});
 const pages=useQuery({queryKey:["seo"],enabled:!!supabase&&role==="admin",queryFn:async()=>{const {data,error}=await supabase!.from("pages_and_seo").select("*").order("updated_at",{ascending:false});if(error)throw error;return data as SeoPage[]}});

 useEffect(()=>{if(settings.data){setAnalytics(settings.data.google_analytics_id||"");setTheme({...defaultTheme,...settings.data.theme_config})}},[settings.data]);

 const saveSettings=useMutation({mutationFn:async()=>{const {error}=await supabase!.from("app_settings").update({google_analytics_id:analytics||null,theme_config:theme}).eq("id",true);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:["settings"]});setToast("تم حفظ الإعدادات بنجاح")},onError:e=>setToast(e.message)});
 const saveAd=useMutation({mutationFn:async()=>{const q=editingAd?supabase!.from("ads_management").update(ad).eq("id",editingAd):supabase!.from("ads_management").insert(ad);const {error}=await q;if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:["ads"]});setAd(emptyAd);setEditingAd(null);setToast("تم حفظ الإعلان")},onError:e=>setToast(e.message)});
 const deleteAd=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase!.from("ads_management").delete().eq("id",id);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:["ads"]});setToast("تم حذف الإعلان")},onError:e=>setToast(e.message)});
 const saveSeo=useMutation({mutationFn:async()=>{const payload={...seo,slug:seo.slug.trim().replace(/^\/+|\/+$/g,""),meta_title:seo.meta_title||null,meta_description:seo.meta_description||null,meta_keywords:seo.meta_keywords||null};const q=editingSeo?supabase!.from("pages_and_seo").update(payload).eq("id",editingSeo):supabase!.from("pages_and_seo").insert(payload);const {error}=await q;if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:["seo"]});setSeo(emptySeo);setEditingSeo(null);setToast("تم حفظ صفحة SEO")},onError:e=>setToast(e.message)});
 const deleteSeo=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase!.from("pages_and_seo").delete().eq("id",id);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:["seo"]});setToast("تم حذف الصفحة")},onError:e=>setToast(e.message)});

 if(!supabase)return <div className="grid min-h-screen place-items-center p-6" dir="rtl"><Card className="w-full max-w-md"><h1 className="mb-2 text-2xl font-bold">إعداد Supabase مفقود</h1><p className="text-slate-600">أضف VITE_SUPABASE_URL و VITE_SUPABASE_ANON_KEY إلى بيئة النشر.</p></Card></div>;
 if(!session)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} onSuccess={s=>setSession(s)} />;

 const nav=[["overview","نظرة عامة",BarChart3],...(role==="admin"?[["settings","الإعدادات",Settings],["theme","المظهر",Palette],["seo","الصفحات و SEO",FileText],["ads","الإعلانات",Megaphone]] as const:[])];
 return <div className="min-h-screen bg-slate-50" dir="rtl">
   {toast&&<div role="status" className="fixed left-4 top-4 z-50 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl">{toast}</div>}
   <div className="mx-auto grid min-h-screen max-w-7xl lg:grid-cols-[240px_1fr]">
    <aside className="border-l border-slate-200 bg-white p-4"><div className="mb-8 flex items-center gap-2"><ShieldCheck className="text-emerald-600"/><div><b>WOW Admin</b><small className="block text-slate-500">{role==="admin"?"مدير":"محرر"}</small></div></div><nav className="grid gap-2">{nav.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={"flex items-center gap-3 rounded-xl px-3 py-3 text-right "+(tab===key?"bg-emerald-600 text-white":"text-slate-700 hover:bg-slate-100")}><Icon size={18}/>{label}</button>)}</nav><Button className="mt-8 w-full" onClick={()=>supabase!.auth.signOut()}><LogOut size={17}/>خروج</Button></aside>
    <main className="p-5 md:p-8"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">لوحة التحكم</h1><p className="text-sm text-slate-500">{session.user.email}</p></div><Button onClick={()=>qc.invalidateQueries()}><RefreshCw size={16}/>تحديث</Button></header>
      {tab==="overview"&&<Overview/>}
      {tab==="settings"&&role==="admin"&&<Card><h2 className="mb-5 text-xl font-bold">الإعدادات العامة والتتبع</h2><form className="grid gap-4" onSubmit={e=>{e.preventDefault();saveSettings.mutate()}}><Field label="Google Analytics ID"><Input value={analytics} onChange={e=>setAnalytics(e.target.value)} placeholder="G-XXXXXXXXXX"/></Field><Button variant="primary" disabled={saveSettings.isPending}>حفظ الإعدادات</Button></form></Card>}
      {tab==="theme"&&role==="admin"&&<Card><h2 className="mb-5 text-xl font-bold">تخصيص المظهر</h2><div className="grid gap-4 md:grid-cols-2"><ColorField label="اللون الرئيسي" value={theme.primary} onChange={v=>setTheme({...theme,primary:v})}/><ColorField label="اللون الثانوي" value={theme.secondary} onChange={v=>setTheme({...theme,secondary:v})}/><ColorField label="الخلفية" value={theme.background} onChange={v=>setTheme({...theme,background:v})}/><ColorField label="سطح البطاقات" value={theme.surface} onChange={v=>setTheme({...theme,surface:v})}/><Field label="الخط"><Input value={theme.font} onChange={e=>setTheme({...theme,font:e.target.value})}/></Field><Field label="نصف قطر العناصر"><Input value={theme.radius} onChange={e=>setTheme({...theme,radius:e.target.value})}/></Field></div><Button className="mt-5" variant="primary" onClick={()=>saveSettings.mutate()}>حفظ المظهر</Button></Card>}
      {tab==="ads"&&role==="admin"&&<div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="mb-5 text-xl font-bold">{editingAd?"تعديل الإعلان":"إضافة إعلان"}</h2><form className="grid gap-4" onSubmit={e=>{e.preventDefault();saveAd.mutate()}}><Field label="مكان العرض"><Select value={ad.placement} onChange={e=>setAd({...ad,placement:e.target.value as Ad["placement"]})}><option value="header">Header</option><option value="body_top">Body Top</option><option value="body_bottom">Body Bottom</option><option value="interstitial">Interstitial</option></Select></Field><Field label="المنصة"><Select value={ad.target_platform} onChange={e=>setAd({...ad,target_platform:e.target.value as Ad["target_platform"]})}><option value="web">Web</option><option value="android">Android</option><option value="both">Both</option></Select></Field><Field label="AdSense Code / AdMob Unit ID"><Textarea rows={6} required value={ad.ad_code} onChange={e=>setAd({...ad,ad_code:e.target.value})}/></Field><label className="flex items-center gap-2"><input type="checkbox" checked={ad.is_active} onChange={e=>setAd({...ad,is_active:e.target.checked})}/>مفعّل</label><Button variant="primary"><Plus size={16}/>{editingAd?"حفظ":"إضافة"}</Button></form></Card><Card><h2 className="mb-5 text-xl font-bold">الإعلانات</h2><ListState loading={ads.isLoading} empty={!ads.data?.length}/>{ads.data?.map(x=><div key={x.id} className="mb-2 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3"><div><b>{x.placement}</b><small className="block text-slate-500">{x.target_platform} · {x.is_active?"مفعّل":"معطّل"}</small></div><div className="flex gap-2"><Button onClick={()=>setAd({...x})}>{<Pencil size={15}/>}تعديل</Button><Button variant="danger" onClick={()=>confirm("حذف الإعلان؟")&&deleteAd.mutate(x.id)}><Trash2 size={15}/>حذف</Button></div></div>)}</Card></div>}
      {tab==="seo"&&role==="admin"&&<div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="mb-5 text-xl font-bold">{editingSeo?"تعديل صفحة":"إضافة صفحة"}</h2><form className="grid gap-4" onSubmit={e=>{e.preventDefault();saveSeo.mutate()}}><Field label="Slug"><Input required value={seo.slug} onChange={e=>setSeo({...seo,slug:e.target.value})}/></Field><Field label="العنوان"><Input required value={seo.title} onChange={e=>setSeo({...seo,title:e.target.value})}/></Field><Field label="المحتوى Rich HTML"><Textarea rows={10} value={seo.content} onChange={e=>setSeo({...seo,content:e.target.value})}/></Field><Field label="Meta Title"><Input value={seo.meta_title||""} onChange={e=>setSeo({...seo,meta_title:e.target.value})}/></Field><Field label="Meta Description"><Textarea rows={3} value={seo.meta_description||""} onChange={e=>setSeo({...seo,meta_description:e.target.value})}/></Field><Field label="Meta Keywords"><Input value={seo.meta_keywords||""} onChange={e=>setSeo({...seo,meta_keywords:e.target.value})}/></Field><label className="flex items-center gap-2"><input type="checkbox" checked={seo.is_published} onChange={e=>setSeo({...seo,is_published:e.target.checked})}/>منشورة</label><Button variant="primary">{editingSeo?"حفظ التعديل":"إضافة الصفحة"}</Button></form></Card><Card><h2 className="mb-5 text-xl font-bold">الصفحات</h2><ListState loading={pages.isLoading} empty={!pages.data?.length}/>{pages.data?.map(x=><div key={x.id} className="mb-2 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3"><div><b>{x.title}</b><small className="block text-slate-500">/{x.slug} · {x.is_published?"منشورة":"مسودة"}</small></div><div className="flex gap-2"><Button onClick={()=>setSeo({...x})}><Pencil size={15}/>تعديل</Button><Button variant="danger" onClick={()=>confirm("حذف الصفحة؟")&&deleteSeo.mutate(x.id)}><Trash2 size={15}/>حذف</Button></div></div>)}</Card></div>}
    </main></div>
 </div>;
}

function Login({email,password,setEmail,setPassword,onSuccess}:{email:string;password:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;onSuccess:(s:Session)=>void}){
 const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 return <div className="grid min-h-screen place-items-center bg-slate-100 p-5" dir="rtl"><Card className="w-full max-w-md"><div className="mb-6 text-center"><ShieldCheck className="mx-auto mb-3 text-emerald-600" size={40}/><h1 className="text-2xl font-bold">تسجيل دخول الإدارة</h1><p className="text-slate-500">WOW Admin Dashboard</p></div><form className="grid gap-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");const {data,error}=await supabase!.auth.signInWithPassword({email,password});if(error)setError(error.message);else if(data.session)onSuccess(data.session);setBusy(false)}}><Field label="البريد الإلكتروني"><Input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="كلمة المرور"><Input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></Field>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button variant="primary" disabled={busy}>{busy?"جارٍ الدخول…":"دخول آمن"}</Button></form></Card></div>
}
function Overview(){return <div className="grid gap-5 md:grid-cols-3"><Card><BarChart3 className="mb-3 text-emerald-600"/><b className="text-lg">نظرة عامة</b><p className="text-sm text-slate-500">لوحة موحدة لإدارة الإعدادات والإعلانات وصفحات SEO.</p></Card><Card><ShieldCheck className="mb-3 text-emerald-600"/><b className="text-lg">RLS</b><p className="text-sm text-slate-500">التعديلات الإدارية محمية بدور admin داخل Supabase.</p></Card><Card><RefreshCw className="mb-3 text-emerald-600"/><b className="text-lg">Realtime</b><p className="text-sm text-slate-500">البيانات قابلة للتحديث الفوري عبر Supabase Realtime.</p></Card></div>}
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><div className="flex gap-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-14 rounded-lg border border-slate-200"/><Input value={value} onChange={e=>onChange(e.target.value)}/></div></Field>}
function ListState({loading,empty}:{loading:boolean;empty:boolean}){if(loading)return <p className="text-sm text-slate-500">جاري التحميل…</p>;if(empty)return <p className="text-sm text-slate-500">لا توجد بيانات بعد.</p>;return null}
export default App;
