"use client";
import {useEffect,useMemo,useState} from "react";import {V2Page} from "@/src/components/V2Page";import {V2Card} from "@/src/components/V2Card";
const TOTAL=604;
export default function Khatma(){const [pages,setPages]=useState(0),[goal,setGoal]=useState(30),[daily,setDaily]=useState(20),[history,setHistory]=useState<Record<string,number>>({});
 useEffect(()=>{try{setPages(Number(localStorage.getItem("wow-khatma")||0));setGoal(Number(localStorage.getItem("wow-khatma-goal")||30));setDaily(Number(localStorage.getItem("wow-khatma-daily")||20));setHistory(JSON.parse(localStorage.getItem("wow-khatma-history")||"{}"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("wow-khatma",String(pages));localStorage.setItem("wow-khatma-goal",String(goal));localStorage.setItem("wow-khatma-daily",String(daily));localStorage.setItem("wow-khatma-history",JSON.stringify(history))},[pages,goal,daily,history]);
 const pct=Math.min(100,pages/TOTAL*100),remaining=Math.max(0,TOTAL-pages),days=Math.ceil(remaining/Math.max(1,daily));
 const today=new Date().toISOString().slice(0,10),todayPages=history[today]||0;
 const add=(n:number)=>{const amount=Math.max(0,Math.min(n,TOTAL-pages));setPages(p=>Math.min(TOTAL,p+amount));setHistory(h=>({...h,[today]:(h[today]||0)+amount}))};
 const dailyDone=todayPages>=daily;
 return <V2Page title="خطة ختم القرآن" subtitle="خطة شخصية لمتابعة صفحات المصحف، مع هدف يومي وسجل محلي محفوظ على جهازك فقط."><V2Card title="تقدم الختمة"><div className="v2-progress"><span style={{width:pct+"%"}}/></div><h3>{pages} / {TOTAL} صفحة · {pct.toFixed(1)}%</h3><p>المتبقي: {remaining} صفحة · المدة التقديرية: {days} يومًا حسب هدفك اليومي</p><div className="v2-form"><button onClick={()=>add(1)} disabled={pages>=TOTAL}>+ صفحة</button><button onClick={()=>add(5)} disabled={pages>=TOTAL}>+ 5 صفحات</button><button onClick={()=>add(10)} disabled={pages>=TOTAL}>+ 10 صفحات</button></div></V2Card><V2Card title="الهدف اليومي"><div className="v2-form"><label>الصفحات يومياً <input type="number" min="1" max="604" value={daily} onChange={e=>setDaily(Math.max(1,Math.min(604,+e.target.value||1)))}/></label><label>مدة الختمة (أيام) <input type="number" min="1" max="604" value={goal} onChange={e=>setGoal(Math.max(1,+e.target.value||1))}/></label></div><p>إنجاز اليوم: {todayPages} / {daily} صفحة {dailyDone?"✓":" "}</p><div className="v2-progress"><span style={{width:Math.min(100,todayPages/daily*100)+"%"}}/></div></V2Card><V2Card title="إدارة الخطة"><button onClick={()=>{if(confirm("هل تريد تصفير سجل الختمة؟")){setPages(0);setHistory({})}}}>بدء ختمة جديدة</button><small>التقدم محفوظ في متصفحك ولا تتم مزامنته بين الأجهزة.</small></V2Card></V2Page>}
