"use client";
import {useEffect,useState} from "react";import {V2Page} from "@/src/components/V2Page";import {V2Card} from "@/src/components/V2Card";
const TOTAL=604;
export default function Khatma(){const [pages,setPages]=useState(0),[targetDays,setTargetDays]=useState(30),[history,setHistory]=useState<Record<string,number>>({}),[loaded,setLoaded]=useState(false);
 useEffect(()=>{try{setPages(Number(localStorage.getItem("wow-khatma")||0));setTargetDays(Number(localStorage.getItem("wow-khatma-days")||30));setHistory(JSON.parse(localStorage.getItem("wow-khatma-history")||"{}"))}catch{}finally{setLoaded(true)}},[]);
 useEffect(()=>{if(loaded){localStorage.setItem("wow-khatma",String(pages));localStorage.setItem("wow-khatma-days",String(targetDays));localStorage.setItem("wow-khatma-history",JSON.stringify(history))}},[pages,targetDays,history,loaded]);
 const pct=Math.min(100,pages/TOTAL*100),remaining=Math.max(0,TOTAL-pages),perDay=Math.ceil(remaining/Math.max(1,targetDays)),d=new Date(),today=[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-"),todayPages=history[today]||0;
 const add=(n:number)=>{const amount=Math.max(0,Math.min(n,TOTAL-pages));setPages(p=>Math.min(TOTAL,p+amount));setHistory(h=>({...h,[today]:(h[today]||0)+amount}))};
 return <V2Page title="خطة ختم القرآن" subtitle="خطة شخصية لمتابعة صفحات المصحف وتحديد مدة الختمة، مع سجل يومي محفوظ محلياً على جهازك."><V2Card title="تقدم الختمة"><div className="v2-progress"><span style={{width:pct+"%"}}/></div><h3>{pages} / {TOTAL} صفحة · {pct.toFixed(1)}%</h3><p>المتبقي: {remaining} صفحة · المطلوب يومياً لإكمالها في المدة: {perDay} صفحة</p><div className="v2-form"><button onClick={()=>add(1)} disabled={pages>=TOTAL}>+ صفحة</button><button onClick={()=>add(5)} disabled={pages>=TOTAL}>+ 5 صفحات</button><button onClick={()=>add(10)} disabled={pages>=TOTAL}>+ 10 صفحات</button></div></V2Card><V2Card title="مدة الختمة والإنجاز اليومي"><div className="v2-form"><label>أريد إكمال الختمة خلال (أيام)<input type="number" min="1" max="604" value={targetDays} onChange={e=>setTargetDays(Math.max(1,Math.min(604,+e.target.value||1)))}/></label></div><p>إنجاز اليوم: {todayPages} صفحة من أصل {perDay} صفحة مقترحة.</p><div className="v2-progress"><span style={{width:Math.min(100,todayPages/Math.max(1,perDay)*100)+"%"}}/></div></V2Card><V2Card title="إدارة الخطة"><button onClick={()=>{if(confirm("هل تريد تصفير سجل الختمة؟")){setPages(0);setHistory({})}}}>بدء ختمة جديدة</button><small>التقدم محفوظ في متصفحك ولا تتم مزامنته بين الأجهزة.</small></V2Card></V2Page>}
