"use client";
import {useEffect,useMemo,useState} from "react";
import {AudioLines,Download,LogIn,RefreshCw,Save,Search,ShieldCheck,Upload} from "lucide-react";
import LivePreview from "../../components/LivePreview";
import {islamwayApi} from "../../lib/islamwayApi";
import {supabase} from "../../lib/supabaseClient";
export default function AdminPage(){
 const [session,setSession]=useState(null),[tab,setTab]=useState("quran"),[readers,setReaders]=useState([]),[q,setQ]=useState(""),[reader,setReader]=useState(null),[surahs,setSurahs]=useState([]),[surah,setSurah]=useState(null),[settings,setSettings]=useState({}),[releases,setReleases]=useState([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const x=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>x.data.subscription.unsubscribe()},[]);
 async function load(){if(!supabase)return;setBusy(true);const [{data:s},{data:r}]=await Promise.all([supabase.from("quran_settings").select("*").limit(1).maybeSingle(),supabase.from("app_releases").select("*").order("created_at",{ascending:false}).limit(5)]);setSettings(s||{});setReleases(r||[]);try{setReaders(await islamwayApi.readers())}catch(e){setMessage(e.message)}setBusy(false)}
 useEffect(()=>{if(session)load()},[session]);
 async function login(e){e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function save(){if(!supabase||!reader||!surah)return;setBusy(true);const {error}=await supabase.from("quran_settings").upsert({id:settings.id||1,default_reader_id:String(reader.id),default_reader_name:reader.name||reader.title,default_surah:Number(surah.id)||1});setMessage(error?error.message:"تم الحفظ بنجاح");setBusy(false)}
 async function chooseReader(r){setReader(r);setBusy(true);try{setSurahs(await islamwayApi.surahs(r.id))}catch(e){setMessage(e.message)}setBusy(false)}
 if(!session)return <main className="min-h-screen bg-zinc-950 p-6 text-white"><form onSubmit={login} className="mx-auto mt-20 max-w-md rounded-2xl border border-zinc-800 bg-zinc-900 p-8"><ShieldCheck className="mb-5 text-emerald-400"/><h1 className="text-2xl font-bold">تسجيل دخول الإدارة</h1><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" className="mt-6 w-full rounded-xl bg-zinc-800 p-3"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور" className="mt-3 w-full rounded-xl bg-zinc-800 p-3"/><button className="mt-4 flex w-full justify-center gap-2 rounded-xl bg-emerald-500 p-3 font-bold text-black"><LogIn size={18}/>دخول</button>{message&&<p className="mt-4 text-red-400">{message}</p>}</form></main>;
 const filtered=readers.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));
 return <main className="min-h-screen bg-zinc-950 p-5 text-white"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold">لوحة تحكم القرآن</h1><p className="text-zinc-500">{session.user.email}</p></div><button onClick={()=>supabase.auth.signOut()} className="rounded-xl border border-zinc-700 px-4 py-2">خروج</button></header><nav className="my-6 flex gap-2"><button onClick={()=>setTab("quran")} className="rounded-xl bg-zinc-800 px-4 py-2">إدارة القرآن</button><button onClick={()=>setTab("apk")} className="rounded-xl bg-zinc-800 px-4 py-2">APK & Releases</button></nav><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5">{tab==="quran"?<><div className="flex justify-between"><h2 className="text-xl font-bold">القراء والسور</h2><button onClick={load}><RefreshCw size={18}/></button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><div className="flex gap-2"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث عن قارئ" className="w-full bg-transparent outline-none"/></div><div className="mt-3 max-h-72 overflow-auto">{filtered.slice(0,50).map(r=><button key={r.id} onClick={()=>chooseReader(r)} className="block w-full rounded-lg p-2 text-right hover:bg-zinc-800">{r.name||r.title}</button>)}</div></div><div><p className="text-sm text-zinc-400">السور</p><div className="mt-3 max-h-72 overflow-auto">{surahs.map(s=><button key={s.id} onClick={()=>setSurah(s)} className="block w-full rounded-lg p-2 text-right hover:bg-zinc-800">{s.name||s.title}</button>)}</div></div></div>{reader&&surah&&<div className="mt-6 rounded-xl bg-zinc-950 p-4"><div className="flex items-center gap-2"><AudioLines size={20}/>{reader.name||reader.title} — {surah.name||surah.title}</div><audio controls className="mt-4 w-full" src={surah.audio_url||surah.url}/><button onClick={save} disabled={busy} className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 font-bold text-black"><Save size={17}/>حفظ كافتراضي</button></div>}</>:<><h2 className="text-xl font-bold">APK & Releases</h2><div className="mt-5 rounded-xl border border-dashed border-zinc-700 p-6 text-center"><Upload className="mx-auto mb-2"/><p className="text-sm text-zinc-400">التوزيع الأساسي عبر GitHub Releases.</p></div><div className="mt-5 space-y-3">{releases.map(r=><article key={r.id} className="rounded-xl bg-zinc-950 p-4"><div className="flex justify-between"><b>v{r.version_name}</b><span>{r.status}</span></div><p className="mt-2 text-sm text-zinc-400">{r.changelog||"بدون وصف"}</p>{r.download_url&&<a href={r.download_url} className="mt-3 inline-flex gap-2 text-emerald-400"><Download size={16}/>APK</a>}</article>)}</div></>}</section><LivePreview settings={settings} release={releases[0]}/></div></div></main>;
}
