"use client";
import {useEffect,useState} from "react";import {V2Page} from "@/src/components/V2Page";import {V2Card} from "@/src/components/V2Card";
type Zikr=readonly [string,number];
const groups:Record<"morning"|"evening"|"sleep",{title:string;items:Zikr[]}>={
 morning:{title:"أذكار الصباح",items:[["أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.",1],["اللهم بك أصبحنا وبك أمسينا وبك نحيا وبك نموت وإليك النشور.",1],["رضيت بالله رباً، وبالإسلام ديناً، وبمحمد ﷺ نبياً.",3],["سبحان الله وبحمده.",100],["لا إله إلا الله وحده لا شريك له، له الملك وله الحمد وهو على كل شيء قدير.",100]]},
 evening:{title:"أذكار المساء",items:[["أمسينا وأمسى الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له.",1],["اللهم بك أمسينا وبك أصبحنا وبك نحيا وبك نموت وإليك المصير.",1],["رضيت بالله رباً، وبالإسلام ديناً، وبمحمد ﷺ نبياً.",3],["سبحان الله وبحمده.",100],["أعوذ بكلمات الله التامات من شر ما خلق.",3]]},
 sleep:{title:"أذكار النوم",items:[["باسمك اللهم أموت وأحيا.",1],["اللهم قني عذابك يوم تبعث عبادك.",3],["سبحان الله.",33],["الحمد لله.",33],["الله أكبر.",34]]}
};
type Group=keyof typeof groups;
export default function Azkar(){const [g,setG]=useState<Group>("morning"),[counts,setCounts]=useState<Record<string,number>>({});useEffect(()=>{try{setCounts(JSON.parse(localStorage.getItem("wow-azkar-counts")||"{}"))}catch{}},[]);useEffect(()=>{localStorage.setItem("wow-azkar-counts",JSON.stringify(counts))},[counts]);const reset=()=>setCounts(p=>({...p,[g]:0}));return <V2Page title="الأذكار" subtitle="أذكار الصباح والمساء والنوم مع عدّاد مستقل لكل ذكر وحفظ التقدم محلياً على جهازك."><div className="v2-tabs">{(Object.keys(groups) as Group[]).map(k=><button className={g===k?"active":""} onClick={()=>setG(k)} key={k}>{groups[k].title}</button>)}</div><V2Card title={groups[g].title}><div className="v2-form"><button onClick={reset}>إعادة عدادات هذا القسم</button><small>يُحفظ التقدم على هذا الجهاز فقط.</small></div>{groups[g].items.map(([text,target],i)=>{const key=g+"-"+i;const count=counts[key]||0;return <div className="v2-zikr" key={key}><p className="v2-arabic">{text}</p><div><small>{count}/{target} مرات</small><button aria-label="زيادة عداد الذكر" onClick={()=>setCounts(p=>({...p,[key]:Math.min(target,(p[key]||0)+1)}))}>{count>=target?"✓":count+" / "+target}</button></div></div>})}</V2Card></V2Page>}
