"use client";
import { useEffect,useState } from "react";
import { LogIn,ShieldCheck,AlertCircle } from "lucide-react";
import { supabase } from "../../../lib/supabaseClient";
const base=process.env.NEXT_PUBLIC_BASE_PATH||"";
export default function Login(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session) window.location.assign(base+"/admin/dashboard/")})},[]);
 async function submit(e){e.preventDefault();setLoading(true);setMessage("");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setMessage(error.message);setLoading(false);return;}const {data:isAdmin,error:rpcError}=await supabase.rpc("is_admin");if(rpcError){setMessage("تعذر التحقق من صلاحية الإدارة: "+rpcError.message);await supabase.auth.signOut();setLoading(false);return;}if(isAdmin!==true){setMessage("تم تسجيل الدخول، لكن هذا الحساب غير مضاف كمسؤول. أضفه إلى user_roles بدور Super Admin أو إلى admin_users.");await supabase.auth.signOut();setLoading(false);return;}window.location.assign(base+"/admin/dashboard/");}
 return <main dir="rtl" className="min-h-screen bg-zinc-950 p-6 text-white"><form onSubmit={submit} className="mx-auto mt-16 max-w-md rounded-3xl border border-zinc-800 bg-zinc-900 p-8"><ShieldCheck className="text-emerald-400" size={32}/><h1 className="mt-4 text-2xl font-bold">تسجيل دخول الإدارة</h1><p className="mt-2 text-sm text-zinc-400">يتم التحقق من جلسة Supabase ثم RPC ‏is_admin.</p><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" className="mt-6 w-full rounded-xl bg-zinc-800 p-3"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور" className="mt-3 w-full rounded-xl bg-zinc-800 p-3"/><button disabled={loading} className="mt-4 flex w-full justify-center gap-2 rounded-xl bg-emerald-500 p-3 font-bold text-black disabled:opacity-50"><LogIn size={18}/>{loading?"جارٍ التحقق…":"دخول"}</button>{message&&<div className="mt-4 flex gap-2 rounded-xl border border-red-900 bg-red-950/30 p-3 text-sm text-red-300"><AlertCircle size={18}/><span>{message}</span></div>}</form></main>}