import Link from "next/link";
import QuranExplorer from "../components/QuranExplorer";
export const metadata={title:"القرآن الكريم | Quran Karim",description:"اقرأ القرآن الكريم واستمع إلى التلاوات."};
export default function Home(){
return <main className="min-h-screen bg-zinc-950 text-white">
<header className="border-b border-zinc-800"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="text-xl font-bold">القرآن <span className="text-emerald-400">الكريم</span></Link><nav className="flex gap-2"><Link href="/quran" className="rounded-xl px-3 py-2 hover:bg-zinc-900">المصحف</Link><Link href="/admin" className="rounded-xl border border-zinc-700 px-3 py-2">الإدارة</Link></nav></div></header>
<section className="mx-auto grid max-w-7xl gap-8 px-5 py-16 md:grid-cols-2 md:py-24"><div className="flex flex-col justify-center"><p className="mb-4 text-sm font-semibold text-emerald-400">بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيمِ</p><h1 className="text-4xl font-black leading-tight md:text-6xl">كتاب الله بين يديك،<br/><span className="text-emerald-400">قراءةً واستماعاً.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">تجربة عربية هادئة لقراءة السور واختيار القارئ والاستماع إلى التلاوات، مصممة للهاتف والحاسوب.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/quran" className="rounded-2xl bg-emerald-500 px-6 py-3 font-bold text-black">ابدأ القراءة</Link><a href="#surahs" className="rounded-2xl border border-zinc-700 px-6 py-3">استكشف السور</a></div></div><div className="rounded-[2rem] border border-emerald-900/50 bg-zinc-900 p-8"><div className="rounded-3xl border border-emerald-800/40 bg-zinc-950 p-8 text-center"><p className="font-serif text-3xl leading-[2.3] md:text-4xl">إِنَّ مَعَ الْعُسْرِ يُسْرًا</p><p className="mt-6 text-sm text-zinc-500">سورة الشرح • 6</p></div></div></section>
<section id="surahs" className="mx-auto max-w-7xl px-5 py-10"><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-emerald-400">المصحف</p><h2 className="mt-1 text-3xl font-bold">اقرأ القرآن الكريم</h2></div><Link href="/quran" className="text-sm text-zinc-400 hover:text-white">فتح المصحف الكامل ←</Link></div><QuranExplorer compact /></section>
<section className="mx-auto grid max-w-7xl gap-5 px-5 py-14 md:grid-cols-3"><div className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><h3 className="text-xl font-bold">قراءة واضحة</h3><p className="mt-3 leading-7 text-zinc-400">نص عثماني مع أرقام الآيات وتجربة RTL كاملة.</p></div><div className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><h3 className="text-xl font-bold">تلاوات إسلام واي</h3><p className="mt-3 leading-7 text-zinc-400">اختيار القراء والاستماع إلى السور عبر Islamway مع تخزين مؤقت.</p></div><div className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><h3 className="text-xl font-bold">سريع ومتجاوب</h3><p className="mt-3 leading-7 text-zinc-400">واجهة خفيفة ومناسبة للاستخدام اليومي على الهاتف والحاسوب.</p></div></section>
<footer className="border-t border-zinc-800"><div className="mx-auto flex max-w-7xl justify-between gap-3 px-5 py-8 text-sm text-zinc-500"><span>القرآن الكريم</span><span>النص: Al Quran Cloud • التلاوات: Islamway</span></div></footer>
</main>;
}