"use client";
import {useEffect,useState} from "react";import {V2Page} from "@/src/components/V2Page";import {V2Card} from "@/src/components/V2Card";
const methods=[["3","رابطة العالم الإسلامي"],["2","الجمعية الإسلامية لأمريكا الشمالية"],["4","أم القرى"],["5","الهيئة المصرية العامة للمساحة"],["12","الاتحاد الإسلامي العالمي"]];
export default function Prayer(){const [city,setCity]=useState("Casablanca"),[country,setCountry]=useState("Morocco"),[method,setMethod]=useState("3"),[data,setData]=useState<any>(),[err,setErr]=useState(""),[loading,setLoading]=useState(false);
 const show=(x:any)=>{setData(x);setErr("")};
 const go=async()=>{setLoading(true);setErr("");try{const r=await fetch("https://api.aladhan.com/v1/timingsByCity?city="+encodeURIComponent(city)+"&country="+encodeURIComponent(country)+"&method="+method);const x=await r.json();if(x.code!==200)throw new Error();show(x.data)}catch{setErr("تعذر جلب المواقيت. تحقق من اسم المدينة والدولة.")}finally{setLoading(false)}};
 const locate=()=>{if(!navigator.geolocation){setErr("الموقع الجغرافي غير مدعوم.");return}setLoading(true);navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch("https://api.aladhan.com/v1/timings/"+Math.round(Date.now()/1000)+"?latitude="+p.coords.latitude+"&longitude="+p.coords.longitude+"&method="+method);const x=await r.json();if(x.code!==200)throw new Error();show(x.data)}catch{setErr("تعذر تحديد المواقيت من الموقع.")}finally{setLoading(false)}},()=>{setErr("لم يسمح المتصفح باستخدام الموقع.");setLoading(false)},{enableHighAccuracy:true,timeout:12000})};
 useEffect(()=>{void go()},[]);
 const labels:Record<string,string>={Fajr:"الفجر",Sunrise:"الشروق",Dhuhr:"الظهر",Asr:"العصر",Maghrib:"المغرب",Isha:"العشاء"};
 return <V2Page title="مواقيت الصلاة" subtitle="احسب مواقيت الصلاة حسب المدينة أو إحداثيات جهازك، واختر طريقة الحساب المناسبة. قد تختلف النتائج باختلاف الجهة المعتمدة."><V2Card title="إعداد الموقع وطريقة الحساب"><div className="v2-form"><label>المدينة<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>الدولة<input value={country} onChange={e=>setCountry(e.target.value)}/></label><label>طريقة الحساب<select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><button onClick={go} disabled={loading}>حساب المدينة</button><button onClick={locate} disabled={loading}>استخدم موقعي</button></div>{err&&<p role="alert">{err}</p>}{loading&&<p>جارٍ حساب المواقيت…</p>}</V2Card>{data&&<V2Card title={data.date?.readable||"مواقيت اليوم"}><p>{data.meta?.timezone||""}</p><div className="v2-prayers">{Object.entries(data.timings||{}).filter(([k])=>Object.hasOwn(labels,k)).map(([k,v])=><div key={k}><b>{labels[k]}</b><strong>{String(v).split(" ")[0]}</strong></div>)}</div><small>طريقة الحساب: {methods.find(x=>x[0]===method)?.[1]}</small></V2Card>}</V2Page>}
